add total today
Ellpeck/ObsidianSimpleTimeTracker pull request #64
Opened 2024-11-14 03:53 UTC by henriwasd

Add Function for sum total the tasks of today

2024-11-14 08:56 UTC, Ellpeck commented
Hi!! Thanks so much for this pull request :)

Please update it so that it doesn't change the formatting of the entire file by removing the semicolons.

2024-11-14 22:44 UTC, henriwasd commented
Adjustment done

2024-11-15 13:00 UTC, Ellpeck requested changes
Thanks!! Just a few more notes now that the diff is a bit clearer to see :)

2024-11-15 14:19 UTC, henriwasd commented on src/tracker.ts
> +    let totalTodayDiv = timer.createEl("div", { cls: "simple-time-tracker-timer" })
Yes, I tested it on mobile, I even use it on mobile too, so it's working fine, but I'm going to implement the function in the options too

2024-11-15 14:34 UTC, henriwasd commented
I added both today's total functions to the API, because I saw that it had both total time functions

2024-11-15 14:56 UTC, Ellpeck approved these changes
Thanks so much, this looks great!!

2024-11-15 14:57 UTC, merged